<template>
  <div>
    <table width='100%' border="1">
      <thead>
        <tr>
          <td>一级指标</td>
          <td>得分</td>
          <td>二级指标</td>
          <td>得分</td>
          <td>三级指标</td>
          <td>得分</td>
        </tr>
      </thead>
      <tbody>
       <tr v-for="(item,index) in tableData[0].firstLever.secondLever[0].thirdLever" :key='index'>
         <td>1</td>
         <td>73.56</td>
         <td>1.1</td>
         <td>84.62</td>
         <td>{{item.name}}</td>
         <td>{{item.score}}</td>
       </tr>
       <tr v-for="(item,index) in tableData[0].firstLever.secondLever[0].thirdLever" :key='index'>
         <td>1</td>
         <td>73.56</td>
         <td>1.1</td>
         <td>84.62</td>
         <td>{{item.name}}</td>
         <td>{{item.score}}</td>
       </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  export default {
    data(){
      return{
        tableData:[
          {
            'firstLever':{
                'name':'1',
                'score':'73.56',
                'secondLever':[{
                  'name':'1.1',
                  'score':'84.64',
                  'thirdLever':[{
                    'name':'1.1.1',
                    'score':'53.85'
                  },{
                    'name':'1.1.2',
                    'score':'100.00',
                  },{
                    'name':'1.1.3',
                    'score':'100.00'
                  }]

                },{
                  'name':'1.2',
                  'score':'74.27',
                  'thirdLever':[{
                      'name':'1.2.1',
                      'score':'100.00'
                    },{
                      'name':'1.2.2',
                      'score':'71.43'
                    },{
                      'name':'1.2.3',
                      'score':'100.00'
                    },{
                      'name':'1.2.4',
                      'score':'100.00'
                    },{
                      'name':'1.2.5',
                      'score':'0.00'
                    }]
                },{
                  'name':'1.3',
                  'score':'75.44',
                  'thirdLever':[{
                    'name':'1.3.1',
                    'score':'100.00'
                  },{
                    'name':'1.3.2',
                    'score':'16.67'
                  },{
                    'name':'1.3.3',
                    'score':'66.67'
                  },{
                    'name':'1.3.4',
                    'score':'100.00'
                  },{
                    'name':'1.3.5',
                    'score':'93.88'
                  }]
                },{
                  'name':'1.4',
                  'score':'37.50',
                  'thirdLever':[{
                    'name':'1.4.1',
                    'score':'100.00'
                  },{
                    'name':'1.4.2',
                    'score':'0.00'
                  },{
                    'name':'1.4.3',
                    'score':'0.00'
                  },{
                    'name':'1.4.4',
                    'score':'50.00'
                  }]
                }]
            }
          },
          {
            'firstLever':{
              'name':'2',
              'score':'82.21',
              'secondLever':[{
                'name':'2.1',
                'score':'66.67',
                'thirdLever':[{
                  'name':'2.1.1',
                  'score':'100.00'
                },{
                  'name':'2.1.2',
                  'score':'0.00'
                },{
                  'name':'2.1.3',
                  'score':'100.00'
                }]
              },{
                'name':'2.2',
                'score':'83.33',
                'thirdLever':[{
                  'name':'2.2.1',
                  'score':'100.00'
                },{
                  'name':'2.2.2',
                  'score':'100.00'
                },{
                  'name':'2.2.3',
                  'score':'50.00'
                }]
              },{
                'name':'2.3',
                'score':'96.00',
                'thirdLever':[{
                  'name':'2.3.1',
                  'score':'100.00'
                },{
                  'name':'2.3.2',
                  'score':'100.00'
                },{
                  'name':'2.3.3',
                  'score':'88.31'
                },{
                  'name':'2.3.4',
                  'score':'95.71'
                }]
              },{
                'name':'2.4',
                'score':'87.78',
                'thirdLever':[{
                  'name':'2.4.1',
                  'score':'100.00'
                },{
                  'name':'2.4.2',
                  'score':'72.22'
                },{
                  'name':'2.4.3',
                  'score':'100.00'
                },{
                  'name':'2.4.4',
                  'score':'100.00'
                },{
                  'name':'2.4.5',
                  'score':'66.22'
                }]
              }]
            }
          },
          {
            'firstLever':{
              'name':'3',
              'score':'82.21',
              'secondLever':[{
                'name':'3.1',
                'score':'66.67',
                'thirdLever':[{
                  'name':'3.1.1',
                  'score':'100.00'
                },{
                  'name':'3.1.2',
                  'score':'0.00'
                },{
                  'name':'3.1.3',
                  'score':'100.00'
                }]
              },{
                'name':'3.2',
                'score':'83.33',
                'thirdLever':[{
                  'name':'3.2.1',
                  'score':'100.00'
                },{
                  'name':'3.2.2',
                  'score':'100.00'
                },{
                  'name':'3.2.3',
                  'score':'50.00'
                }]
              },{
                'name':'3.3',
                'score':'96.00',
                'thirdLever':[{
                  'name':'3.3.1',
                  'score':'100.00'
                },{
                  'name':'3.3.2',
                  'score':'100.00'
                },{
                  'name':'3.3.3',
                  'score':'88.31'
                },{
                  'name':'3.3.4',
                  'score':'95.71'
                }]
              },{
                'name':'3.4',
                'score':'87.78',
                'thirdLever':[{
                  'name':'3.4.1',
                  'score':'100.00'
                },{
                  'name':'3.4.2',
                  'score':'72.22'
                },{
                  'name':'3.4.3',
                  'score':'100.00'
                },{
                  'name':'3.4.4',
                  'score':'100.00'
                },{
                  'name':'3.4.5',
                  'score':'66.22'
                }]
              }]
            }
          }
        ]
      }
    },



    methods: {
      showList(){
        console.log(this.tableData)
      }
    },
    mounted() {
      this.showList()
    },
  }
</script>

<style scoped>
  *{
    margin:0;
    padding:0;
  }
  table{
    border-collapse: collapse;
  }
</style>